### ISSUE TITLE
Features page - Frontend inconsistencies

### ISSUE THREAD

**Issue by VictorMita** [arkemishub/arke-website#11]
**Describe the bug**
Design/Frontend bugs

**To Reproduce**
All the screens show the problems

**Expected behaviour**
Frontend should be near to pixel-perfect

**Desktop:**
- OS: MacOS
- Browser: Chrome

**Bugs**

- [x] Missing sub bar in the header (Ask Victor for references)
<img width="1663" alt="Screenshot 2023-05-02 at 15 19 22" src="https://user-images.githubusercontent.com/28099874/235691522-73bb457f-30e5-463e-bb39-4a2dfca3b22c.png">

- [x] All screen hero component
![Screenshot 2023-05-02 at 15 20 45](https://user-images.githubusercontent.com/28099874/235691655-1de28ed2-ef01-4d8e-b7cd-d1ff95ff8b30.png)

- [x] Completely different layout compared to the Figma design
<img width="1662" alt="Screenshot 2023-05-02 at 15 21 33" src="https://user-images.githubusercontent.com/28099874/235691775-d7db96d6-93cf-4b21-99fa-41b613f22ccf.png">

- [x] Wrong stroke
<img width="1641" alt="Screenshot 2023-05-02 at 15 22 04" src="https://user-images.githubusercontent.com/28099874/235691834-5d470fe5-a454-42c5-8b86-b92a14bbffe8.png">

- [x] Wrong margins
<img width="1444" alt="Screenshot 2023-05-02 at 15 22 27" src="https://user-images.githubusercontent.com/28099874/235691903-ce24ff58-ced0-44c1-b88c-4f6347f7eb32.png">

- [x] Wrong radius of box corners
<img width="575" alt="Screenshot 2023-05-02 at 15 23 08" src="https://user-images.githubusercontent.com/28099874/235692011-07f3ef55-6a13-4e13-b393-d0b828b09f4d.png">

- [x] Missing buttons behaviour and animation (Ask Victor for references)
<img width="1425" alt="Screenshot 2023-05-02 at 15 23 34" src="https://user-images.githubusercontent.com/28099874/235692119-89447a6d-4bf5-45fc-abfd-5b457c7b221f.png">

- [x] Wrong component width (should be same as header)
![Screenshot 2023-05-02 at 15 24 02](https://user-images.githubusercontent.com/28099874/235692742-121dcd65-e5a6-4ec0-8b2a-34a6c69e0442.png)

- [x] Wrong screenshot
<img width="1505" alt="Screenshot 2023-05-02 at 15 24 56" src="https://user-images.githubusercontent.com/28099874/235692840-87bd3133-e600-4b53-9b0c-37ed762d9c22.png">

- [x] Wrong blur
<img width="1486" alt="Screenshot 2023-05-02 at 15 25 23" src="https://user-images.githubusercontent.com/28099874/235692961-c713e07a-8e65-4877-a1f3-001b7a962aa0.png">

- [x] New lines for text
<img width="1487" alt="Screenshot 2023-05-02 at 15 25 39" src="https://user-images.githubusercontent.com/28099874/235693036-a1ba7bdf-2c29-4180-a763-93fe7ca6e661.png">

- [x] Missing lines in the component
<img width="1510" alt="Screenshot 2023-05-02 at 15 26 12" src="https://user-images.githubusercontent.com/28099874/235693115-063bceba-5d30-4a65-ab54-4d762a647c1b.png">

- [x] Missing shade
<img width="1588" alt="Screenshot 2023-05-02 at 15 26 43" src="https://user-images.githubusercontent.com/28099874/235693209-1c30599e-ee76-4648-9c9e-6a28dcfd0238.png">

- [ ] Wrong layout and behaviour 
<img width="1621" alt="Screenshot 2023-05-02 at 15 27 12" src="https://user-images.githubusercontent.com/28099874/235693283-f5642e78-7ef5-4900-ab47-40232e96dacf.png">

- [x] Wrong content text
<img width="1601" alt="Screenshot 2023-05-02 at 15 29 20" src="https://user-images.githubusercontent.com/28099874/235693345-e4f6d1b6-aaf4-42cf-9ecb-38dffffadc30.png">

- [x] New lines
<img width="1609" alt="Screenshot 2023-05-02 at 15 29 53" src="https://user-images.githubusercontent.com/28099874/235693483-938a16d1-dec3-4445-aa1c-dd21c75d7768.png">

**Comment by karim-hajouan** [comment]
Fix: complete tasks to resolve inconsistencies in features page
